### PR TITLE
Enable end-to-end riscv tests in CI

### PR DESCRIPTION
**Pull request by patrick-rivos**
Add `examples_riscv_tests.py` which is based on `examples_power_tests.py` to run riscv end to end testing in the CI.

This commit is stacked on top of https://github.com/IBM/microprobe/pull/47. Once merged, this change can be rebased to remove the extra commit.

### CODE REVIEW

**Review by rbertran — APPROVED** [review]

**Comment by patrick-rivos** [comment]
Rebased to be 1 commit

**Comment by rbertran** [comment]
Please, make sure that all commits are signed in the future. Thanks a lot!

**Comment by patrick-rivos** [comment]
I just set up my gpg key so they'll be signed from here on out - thank you for the quick reviews!

**Comment by rbertran** [comment]
thank to you for the contributions ;)

**Pull request merged**
