### PR TITLE
Improve processing of binary regions in Microprobe Test (MPT) files

### PR DESCRIPTION
**Pull request by ArnauBigas**
Before this change, it was assumed that MPT files contained one instruction per line (in assembly or binary). If the code was in binary, then it was also assumed that the data would come in the correct sizes (i.e. the right instruction codification length).

However, this is not the case as Microprobe supports the decodification of binary streams of instructions of arbitrary lengths. Splitting the data into the appropiate lengths is therefore not the responsibility of the program generating the MPT, but  icroprobe's.

This commit changes the code so that the internal representation of MPT files contains both assembler code and binary code data in separate data structures to be processed separately (i.e. by utils/asm.py and utils/bin.py respectively).

Note that, although combining assembly and binary data in the MPT files is technically supported, the tool for generating C files
out of MPTs won't order those instructions correctly. I am not sure if this is a common use case or not. If necessary, this feature would be implemented in a later time (i.e. before accepting this Pull Request).

### CODE REVIEW

**Comment by rbertran** [comment]
Uops, my fault @ArnauBigas , I had a solution implemented and I was waiting for the internal CI to confirm changes... 
I apologize since I should have notified you about my intentions.  

Looking at your proposal, it looks good too. 

- MPT parsing is extended with the concept of 'code regions' if a binary codified instruction is found. Not sure (yet) if this change will have implications in other tools that use MPTs as input.
- mp_mpt2c tool is extended to process instructions first and then the code regions. I think it needs some fixes to keep the addresses/code layout information.

My approach was slightly different. I did not extend the MPT format and I just added a flag `--raw-bin` in the tool to change to processing mode. If so, contiguous entries in the code were lumped together and then processed. Another flag `--safe-bin` was added to avoid failures when interpreting data dumped as code. This keeps the old behavior (i.e. the assumption that one line in the mpt is one instruction) and allows the new processing when a MPT is generated via ChopStiX (or other tools dumping raw binary). 

Since, both approaches look reasonable, so I'll test both in my internal CI which tests other backends (powerpc and s390) and decide based the outcome.

**Comment by ArnauBigas** [comment]
Don't worry, @rbertran . These changes allowed me to identify different areas of the workflow which needed to be fixed in order to achieve our goals, so there is no need for an apology. More over, I think my communications should improve too before dumping a bunch of pull requests :')

Your overview of my implementation is quite accurate, and you are right about the layout of the information quite possibly needing some more work. I also implemented a `--safe-bin` flag internally, but hadn't pushed it yet. I wanted to open up issue to talk about it, since I have some concerns about its implementation (of the "safe" functionality, not the flag's).

Update me when the tests results come back!

**Comment by rbertran** [comment]
Latest commit (01fa4dc4535c2f71099da7b7b1dc594f9907a55c)  should fix several issues and avoids problems with other internal tools that this PR generates.

mp_mpt2c now has two parameters `--safe-bin`  and `--raw-bin` that should be used for processing MPT generated with raw dumps using [chopstix](https://github.com/IBM/chopstix/) tool. If that solved the problems, this PR will be closed.

**Comment by ArnauBigas** [comment]
The latest commit seems to have broken the instruction decoding, most of the instructions which were previously decoded are now raw bytes. I am investigating why, I'll get back to you once I have figured it out.

**Comment by ArnauBigas** [comment]
The commit you mention appears to have resolved this issue, I am able to reproduce the behaviour of the code in this PR with the code in master. I am closing this PR, thank you.

**Pull request closed without merging**
